### ISSUE TITLE
Sign off on acceptance criteria

### ISSUE THREAD

**Issue by u20437863-James-Butler** [COS-301/graduates#1204]
Sign off on the acceptance criteria to finish off the mini project

**Comment by Ponalo-ss** [comment]
[Acceptance Criteria Checklist.pdf](https://github.com/COS-301/graduates/files/8533253/Acceptance.Criteria.Checklist.pdf)
Feature Sign off based on Acceptance criteria

**Comment by u20437863-James-Butler** [comment]
Looks good. I'll move this issue to done.
