### ISSUE TITLE
ER diagram for the database

### ISSUE THREAD

**Issue by ZoeLiebenberg** [COS-301/graduates#139]
**Task**: create an ER diagram to represent the database that the team will interact with

**Comment by LarisaBothaTuks** [comment]
This is the relation I proposed to the data engineers. The final ER diagram has been uploaded to the wiki
![Entity Relationship Diagram1](https://user-images.githubusercontent.com/94512917/159227434-a31d4a00-6ed7-4f53-a2d9-9721f7c61ca0.png)
