### ISSUE TITLE
(docs): Add design consideration for Student requesting info in doc

### ISSUE THREAD

**Issue by LiamBurgess18015001** [COS-301/graduates#178]

**Comment by dylan2894** [comment]
The following design consideration was added to the SRS:

• Will other graduates be able to view the Request for Access feature and access re-
sources of fellow graduates? In conclusion, it seems counter-intuitive to allow fellow
graduates to access each other’s resources. Only companies should be able to request
and access graduate resources.
  
        – Therefore, the addition of a check to verify if the current user is using a company
        representative profile must be performed. If the user is a graduate, the Request for
        Access feature should not appear on the relevant graduate’s profile page. Gradu-
        ate’s should not be able to access each other’s resources.
        
        – Implementations of future versions may wish to allow graduates to access one
        another’s resources
