### ISSUE TITLE
Compile team wiki for demo

### ISSUE THREAD

**Issue by u20437863-James-Butler** [COS-301/graduates#225]
We need to compile this document of what has been completed so far, for the Friday demo. Ponalo and I will do everything on the functional requirements side, and each of you will fill in what you have completed so far.

**Comment by thangeniFT** [comment]
so everyone is gonna fill in their part then we submit it as one as well as pushing it to GitHub- no need to push it individually?

**Comment by u20437863-James-Butler** [comment]
This document is for the demo on Friday to record our progress. You will put an explanation of what you have implemented or documented in here. The actual implementation or documentation will be pushed to GitHub by you. So for example if I need to document how to do the login I will post my plan to do the login on the wiki and I will write a summary of what I have done, including that plan to this document
