### ISSUE TITLE
Documentation and diagrams for offline requirement and service worker

### ISSUE THREAD

**Issue by Ivy-leet** [COS-301/graduates#294]
Post documentations and diagrams here for review, additions and correction. Documentation and diagrams to be finalized before Friday morning.

**Comment by Ivy-leet** [comment]
Please view comments added in the document.
[Service Worker Documentation.docx](https://github.com/COS-301/graduates/files/8332560/Service.Worker.Documentation.docx)

**Comment by QabaNjabulo** [comment]
[Activity_Diagram_.pdf](https://github.com/COS-301/graduates/files/8333526/Activity_Diagram_.pdf)

**Comment by Ivy-leet** [comment]
@Kajal022 With reference to the Cache section of Documentation_v1.docx, are all the different caching strategies listed. If so, should I also provide formal documentation about caching API requests and responds?

**Comment by Kajal022** [comment]
@Ivy-leet  I just realized that I forgot to add the part about lazy caching and prefetched caching. I will do that now. I did add some information about caching API on page 5 but I think adding more to it will help.

**Comment by Kajal022** [comment]
This is the updated document. @Ivy-leet  please add the formal documentation about caching API to this document. If possible could you also please add information about why we chose to use prefetched and lazy caching on page 6
[Documentation_v2.docx](https://github.com/COS-301/graduates/files/8335938/Documentation_v2.docx)

**Comment by Ivy-leet** [comment]
@Kajal022
[Caching GraphQL APIs.docx](https://github.com/COS-301/graduates/files/8335975/Caching.GraphQL.APIs.docx)

**Comment by Kajal022** [comment]
Yes please

**Comment by Ivy-leet** [comment]
@QabaNjabulo Please send the Activity Diagram in PNG format

**Comment by QabaNjabulo** [comment]
![Activity_Diagram_](https://user-images.githubusercontent.com/94046613/159786965-1f380fa7-acee-4f87-bc32-c831b8b11d8b.png)

**Comment by Ivy-leet** [comment]
Please review the recent version and comment for any additions or changes. React with thumbs up if you are satisfied with the documentation.
One more thing that I wanted us to discuss is the caching method we are going to use. If you feel like this is meant for a separate issue please create it.
[Documentation_v3.docx](https://github.com/COS-301/graduates/files/8336308/Documentation_v3.docx)
.

**Comment by Ivy-leet** [comment]
Final documentation for service workers and offline requirement.
[Documentation_v3.docx](https://github.com/COS-301/graduates/files/8340406/Documentation_v3.docx)
