### ISSUE TITLE
(designs): Wireframe and mockups 

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#35]
Wireframe the front-end and design some mockups

Due: 19/03/2022

**Comment by dylan2894** [comment]
![Request-Access-Feature-Wireframe](https://user-images.githubusercontent.com/61905387/158586504-41001b78-8863-4c8d-8170-3f8ec966b702.png)
![Student Profiles + RFA Wireframes](https://user-images.githubusercontent.com/61905387/158586530-4d1b1e98-d78f-4d69-a89b-b931cd6fa098.png)

Finished Wireframing for the Request for Access feature. Busy with Mockups next...
The Student Profile Page feature wireframe contains the Request for Access wireframe. (see above)

**Comment by dylan2894** [comment]
![Request-Access-Feature-Wireframe](https://user-images.githubusercontent.com/61905387/158586504-41001b78-8863-4c8d-8170-3f8ec966b702.png)
![Student Profiles + RFA Wireframes](https://user-images.githubusercontent.com/61905387/158586530-4d1b1e98-d78f-4d69-a89b-b931cd6fa098.png)

The finished **final** wireframe for the Request for Access feature. Busy with Mockups next...
The Student Profile Page feature wireframe contains the Request for Access wireframe. (see above)

**Comment by dylan2894** [comment]
**Final** wireframe for the Request for Access feature.
The "transcripts" and "certificates" sections were added. The order of the items was changed to match that of the Storage feature's page.
![RFA Wireframe v2](https://user-images.githubusercontent.com/61905387/159124043-bc55d1ef-0a7a-4311-86cb-0628dbae9dc2.PNG)
![Student Profile + RFA Wireframe v2](https://user-images.githubusercontent.com/61905387/159124046-2a4a05a1-7114-45f7-ae4e-93349c6558c4.png)

**Comment by dylan2894** [comment]
**Final** wireframe. Redesign of the checkbox functionality into buttons instead as it is a lot cleaner.

![RFA Wireframe v3](https://user-images.githubusercontent.com/61905387/159131427-d6280d96-b08b-430c-98b5-61397eed5c95.png)
![Student Profile + RFA Wireframe v3](https://user-images.githubusercontent.com/61905387/159131432-6c200e0e-7060-425d-9e02-468281b2a2ac.png)

**Comment by dylan2894** [comment]
**Final** Mockup :

![RFA Mockup Final](https://user-images.githubusercontent.com/61905387/159131445-f4f78ce7-45e8-443d-81db-fab070af6f77.PNG)

**Comment by dylan2894** [comment]
Wireframe v4.0 for the web. Reduced the text in the button from "Request Access" to "Request".

![RFA Wireframe v4](https://user-images.githubusercontent.com/61905387/159473905-131e95e5-1b75-4e1f-a115-e52e74cd22cd.png)
![Student Profile + RFA Wireframe v4](https://user-images.githubusercontent.com/61905387/159473937-80f3251b-3510-4dd4-916c-23148ff446e2.png)

**Comment by dylan2894** [comment]
Final Mockup (v3) : 
![RFA Mockup Web v3](https://user-images.githubusercontent.com/61905387/159475228-363eca15-443c-4d3c-8952-daca390508a1.PNG)

**Comment by dylan2894** [comment]
Final Mockup (v3) as seen within the Graduate's profile page:

![RFA Mockup Web v3](https://user-images.githubusercontent.com/61905387/159516189-ed0a3bef-a3c4-47cc-8971-88576fccb3b1.png)

**Comment by dylan2894** [comment]
Final Mobile Mock-up:

![RFA Mockup Mobile v2](https://user-images.githubusercontent.com/61905387/159538447-ab97cf6f-8be8-4d56-afaa-18c658ee3935.png)

Final Mobile Mock-up as seen within the Graduate profile page:

![Mobile + RFA Mockup](https://user-images.githubusercontent.com/61905387/159538554-30d10299-b78b-44a8-90a6-eb9d9579009e.PNG)
