### ISSUE TITLE
(docs): Schema diagrams for API Calls. Diagram for model of end points

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#37]
See group recording for additional information. 
Document the planned endpoints

Due: 19/03/22

**Comment by LiamBurgess18015001** [comment]
A UML of the possible API queries. This can likely be auto generated by GraphQL

**Comment by LiamBurgess18015001** [comment]
Schema

![image](https://user-images.githubusercontent.com/73439224/159011835-5003c767-a5f8-4648-b914-814465b778b7.png)

**Comment by LiamBurgess18015001** [comment]
> A UML of the possible API queries. This can likely be auto generated by GraphQL

Apologies that is vague. 
1. Generate schemas like above of the possible different calls and their responses that our API will make i.e. What will the request look like when sent to the backend. What will the response look like.
