### ISSUE TITLE
(docs): Formulate testing plan

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#40]
Investigate and formulate testing plan for the project. Textbook has additional information.

Due: 20/03/22

**Comment by LiamBurgess18015001** [comment]
https://www.guru99.com/what-everybody-ought-to-know-about-test-planing.html

**Comment by LiamBurgess18015001** [comment]
From version one of your testing plan I want you to iterate and make a more detailed version two. You can do it like above for now. You can keep step 1 (Analyze the product) brief but the rest should be more detailed.
