### ISSUE TITLE
(docs): Compile functional requirements (SRS) and the project plan

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#41]
Due: 19/03/22

**Comment by LiamBurgess18015001** [comment]
![image](https://user-images.githubusercontent.com/73439224/158956012-ae7c5708-f5d9-4385-94fe-41317f83a4ea.png)

**Comment by LiamBurgess18015001** [comment]
I will need to add ontop of this a small description of business needs as the lecturer implies this in lecture 3

**Comment by LiamBurgess18015001** [comment]
This document will then be compiled with the design, architecture and other documents/models into one presentation document for friday.

**Comment by LiamBurgess18015001** [comment]
The compiled document should show the iterative documentation of the system as a whole.
Thus it may have repeated sections to help prove the case of working as a group for sprint 1's marking on friday

**Comment by LiamBurgess18015001** [comment]
![image](https://user-images.githubusercontent.com/73439224/158961105-6f7bb918-b912-4605-9e67-2a10950a997b.png)

**Comment by LiamBurgess18015001** [comment]
Doc 1: System requirements definition (Business needs, SRS, Feasibility study, Project plan)
Doc 2: System modelling and design doc (Decomposition, Architecture, Model, Diagrams)
