### ISSUE TITLE
(docs): Compile each members design docs

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#42]
Compile the docs related to the initial work.

Look at all our [issues related to docs](https://github.com/COS-301/graduates/issues?q=is%3Aopen+is%3Aissue+project%3Acos-301%2Fgraduates%2F15+label%3Atype%3Adocumentation)

Due: 20/03/22

**Comment by dylan2894** [comment]
Wireframes added in the comments of the issue: **(designs): Wireframes and Mockups** 👍

**Comment by LiamBurgess18015001** [comment]
First compilation attempt will be the 20th and the finalization 22/23rd
