### ISSUE TITLE
Get a list of all operations that we need to do

### ISSUE THREAD

**Issue by MildogMiller** [COS-301/graduates#428]
get a general list of all the functions that we can do

**Comment by Xander-FP** [comment]
Here is a list of functions more or less mapped to possible api endpoints:

Insert and Update: can use the same api endpoint where information that is not given is not set/changed -> setStudentProfile{...}
Read: Returns either one or many students based on parameters getStudentProfile(studentNum){...} + getStudentProfiles(params) where params = [tags]/Prefered location/Has permission to view documents/
Delete: deleteStudentProfile(studentNum){}

Do we need anything else @David-Roodt @MildogMiller?
