### ISSUE TITLE
(docs): stories of how Request for Access works

### ISSUE THREAD

**Issue by arulagrawal** [COS-301/graduates#44]
Due: 19/03/22

**Comment by LiamBurgess18015001** [comment]
I have compiled on the feature team page stories (use cases) of our feature and tried to detail the technical process for those to use as reference for their diagrams and docs

**Comment by LiamBurgess18015001** [comment]
Please comment on the page on our team page with any questions or suggestions

**Comment by arulagrawal** [comment]
The stories page: https://github.com/orgs/COS-301/teams/c/discussions/2
