### ISSUE TITLE
Documentation and Diagrams must be completed

### ISSUE THREAD

**Issue by u20437863-James-Butler** [COS-301/graduates#547]
The relevant diagrams and design documents must be completed or touched up and deposited in the wiki. The wiki page should also be updated to include sections for each doc and the plans for future teams.

**Comment by Ponalo-ss** [comment]
![Graduate's Personal Details drawio](https://user-images.githubusercontent.com/94800625/163277149-f86d7f31-0d4d-4c51-8af2-63d74b6d7d10.png)

**Comment by Ponalo-ss** [comment]
![Academic Details drawio](https://user-images.githubusercontent.com/94800625/163278285-9e90b277-3a76-4558-bc1d-eff8469b6943.png)

**Comment by Ponalo-ss** [comment]
![Qualification drawio](https://user-images.githubusercontent.com/94800625/163278316-2bf16931-537a-4ab1-97ff-f282fbb1c4e5.png)

![UP Integration drawio](https://user-images.githubusercontent.com/94800625/163278350-21e85bfc-f5cc-457e-bba9-e4c4a1082de2.png)
