### ISSUE TITLE
Create mockups for Student Requests/Student Responses

### ISSUE THREAD

**Issue by anru123** [COS-301/graduates#585]

**Comment by Aramnand** [comment]
![image](https://user-images.githubusercontent.com/100368346/162824163-4a1752ba-2fea-4988-9a42-f1ac00a1169c.png)

![image](https://user-images.githubusercontent.com/100368346/162824186-6d0425d8-4009-49e3-8faa-91b0e47413e9.png)

**Comment by Aramnand** [comment]
Mockups were created and published on the design wiki for the notification feature.
